config/routes.rb
Mew::Application.routes.draw do

  ActiveAdmin.routes(self)
  namespace :api, :constraints => {:format => /(json)/} do
    namespace :v1 do
      devise_for :users, controllers: {:sessions => 'api/v1/users/sessions'}
      resources :meters, only: [:create]
      
      resources :measurements, only: [:create, :show, :index, :update]
      resources :communication_devices, only: [:create, :show, :update]

      resources :reports
      match '/reports/:id/run' => 'reports#run', via: [:get], as: :api_v1_run_report
    end
  end

  resources :case_managers do 
    resources :managed_members, only: [:index, :create, :destroy]
  end

  resources :member_groups, except: [:show] do
    resources :grouped_members, only: [:index, :create, :destroy]
  end

  resources :reports

  resources :members do
    resources :email_messages, only: [:index, :create, :new, :show]
    resources :measurements
    resources :case_managers, only: [:index]
  end

  devise_for :users, controllers: {:sessions => 'users/sessions', :registrations => 'users/registrations'}
  resources :communication_devices
  resources :meters

  root 'high_voltage/pages#show', id: 'home'
end

app/models/member_group.rb
class MemberGroup < ActiveRecord::Base
	validates :name, presence: true
	validates :description, presence: true

  belongs_to :created_by, class_name: "CaseManager"
	
	has_many :grouped_members


  def self.mine(case_manager)
      where("created_by = ?", case_manager.id)
  end

end

app/controllers/member_groups_controller.rb
class MemberGroupsController < ApplicationController
  before_action :set_member_group, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!

  load_and_authorize_resource

  # GET /member_groups
  def index
    @member_groups = MemberGroup.where(created_by: current_user)

    respond_to do |format|
      format.html # show.html.erb
      format.json
    end
  end

  # GET /member_groups/new
  def new
    @member_group = MemberGroup.new
  end

  # GET /member_groups/1/edit
  def edit
  end

  # POST /member_groups
  def create
    @member_group = MemberGroup.new(member_group_params)
    @member_group.created_by = current_user
    if @member_group.save
      redirect_to member_group_grouped_members_path(@member_group)
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /member_groups/1
  def update
    if @member_group.update(member_group_params)
      redirect_to @member_group, notice: 'Member group was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /member_groups/1
  def destroy
    @member_group.destroy
    redirect_to member_groups_url, notice: 'Member group was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member_group
      @member_group = MemberGroup.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def member_group_params
      params.require(:member_group).permit(:name, :description)
    end
end

app/helpers/member_groups_helper.rb
module MemberGroupsHelper
end

app/views/member_groups/_form.html.erb
<%= simple_form_for(@member_group) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <label for="title"><%= f.label :name %></label>
    <%= f.text_field :name, :class => "form-control", :placeholder => "Enter name"  %>
  </div>

  <div class="form-group">
    <label for="title"><%= f.label :description %></label>
    <%= f.text_field :description, :class => "form-control", :placeholder => "Enter description"  %>
  </div>

  <div class="actions">
    <%= f.button :submit, class: "btn btn-default" %>
  </div>
<% end %>

app/views/member_groups/edit.html.erb
<h1>Editing Member group</h1>

<%= render 'form' %>

<%= link_to 'Show', @member_group %> |
<%= link_to 'Back', member_groups_path %>

app/views/member_groups/index.html.erb
<div ng-controller="MemberGroupsTableCtrl" ng-cloak>
  <h1><i class="fa fa-users"></i> Member Groups</h1>

  <div class="row">
    <div class="form-group">
      <label class="col-md-1 control-label search-label">Find</label>
      <div class="col-md-10">
        <input type="search" ng-model="filter.$" class="form-control search-box" />
      </div>
    </div>
  </div>

  <table class='table' ng-table="tableParams">
    <tbody>
        <tr ng-repeat="member_group in $data">
          <td data-title="'Name'" sortable="'name'" data-ng-bind-html="member_group.links.show"></td>
          <td data-title="'Description'" sortable="'description'">{{member_group.description}}</td>
          <td data-title="'Number of Members'" sortable="'number_of_members'">{{member_group.number_of_members}}</td>
          <td data-ng-bind-html="member_group.links.grouped_members"></td>
        </tr>
    </tbody>
  </table>
  <p><strong>Total member groups:</strong> {{tableParams.total()}}</p>
</div>
<br>

<%= link_to 'New member group', new_member_group_path %>

app/views/member_groups/new.html.erb
<h1>New Member group</h1>

<%= render 'form' %>

<%= link_to 'Back', member_groups_path %>

app/views/member_groups/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_member_group_path(@member_group) %> |
<%= link_to 'Back', member_groups_path %>