config/routes.rb
Mew::Application.routes.draw do

  ActiveAdmin.routes(self)
  namespace :api, :constraints => {:format => /(json)/} do
    namespace :v1 do
      devise_for :users, controllers: {:sessions => 'api/v1/users/sessions'}
      resources :meters, only: [:create]
      
      resources :measurements, only: [:create, :show, :index, :update]
      resources :communication_devices, only: [:create, :show, :update]

      resources :reports
      match '/reports/:id/run' => 'reports#run', via: [:get], as: :api_v1_run_report
    end
  end

  resources :case_managers do 
    resources :managed_members, only: [:index, :create, :destroy]
  end

  resources :member_groups, except: [:show] do
    resources :grouped_members, only: [:index, :create, :destroy]
  end

  resources :reports

  resources :members do
    resources :email_messages, only: [:index, :create, :new, :show]
    resources :measurements
    resources :case_managers, only: [:index]
  end

  devise_for :users, controllers: {:sessions => 'users/sessions', :registrations => 'users/registrations'}
  resources :communication_devices
  resources :meters

  root 'high_voltage/pages#show', id: 'home'
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
  include Archivable
	validates :glucose_value, presence: true, numericality: { greater_than_or_equal_to: 10, less_than_or_equal_to: 500 }
  validates :measured_at, presence: true
  validates :hash, presence: true
	validates :code_number, presence: true
	validates :reading_type, presence: true, inclusion: { in: %w(AC Normal PC QC), message: "%{value} is not AC, Normal, PC, or QC." }
	validates :meter_id, presence: true, unless: :case_manager_id
  validates :case_manager_id, presence: true, unless: :meter_id
  validates :member_id, presence: true
  validate :measurement_must_be_unique

	belongs_to :communication_device
	belongs_to :meter
  belongs_to :member
  belongs_to :case_manager

  before_create :set_preferred_meter, :measurement_must_be_unique
  before_validation :set_token

  def self.mine(user)
  	where(member: user)
  end	

  def set_preferred_meter
    member.update_attributes(preferred_meter_id: self.meter.id) if meter
  end

  def display_name
    "#{glucose_value} mg/dL at #{measured_at.strftime('%-m/%e/%y %l:%M %P')}"
  end

  def generate_token
    Digest::MD5.hexdigest "#{self.measured_at}-#{self.meter.bluetooth_mac}"
  end

  def retrieved_at_in_zone
    t = self.retrieved_at
    DateTime.new(t.year,t.month,t.day,t.hour,t.min,t.sec, "#{self.retrieved_at_time_zone.to_i/60/60}") + self.retrieved_at_time_zone.to_i.seconds
  end

  def measured_at_in_zone
    t = self.measured_at
    DateTime.new(t.year,t.month,t.day,t.hour,t.min,t.sec, "#{self.measured_at_time_zone.to_i/60/60}") + self.measured_at_time_zone.to_i.seconds
  end

  private
  def measurement_must_be_unique
    if Measurement.where("token = ? and id != ?", self.token, self.id).count > 0
      errors.add(:token, "must be unique")
    end
  end

  def set_token
    if self.token.blank? and self.meter
      self.token = self.generate_token
    end
  end
  
  
end

app/controllers/api/v1/measurements_controller.rb
class API::V1::MeasurementsController < ApplicationController
  before_action :set_measurement, only: [:index, :show, :update]

  skip_before_filter :verify_authenticity_token

  before_filter :authenticate_user_from_token!
  before_filter :authenticate_user!

  load_and_authorize_resource

  respond_to :json

  # GET /measurement
  def index
    @measurements = Measurement.mine(current_user).where(archived_at: nil)
  end

  # GET /measurements/1
  def show
    
  end

   # PATCH/PUT /measurements/1
  def update
    @errors = @measurement.update(measurement_params) ? nil : @measurement.errors.full_messages.to_sentence
    render :show
  end

  # POST /measurements
  def create
    @measurement = Measurement.new(measurement_params)
    @measurement.member = current_user
    @measurement.retrieved_at_time_zone = (DateTime.iso8601 params[:measurement][:retrieved_at]).utc_offset
    @measurement.measured_at_time_zone = (DateTime.iso8601 params[:measurement][:measured_at]).utc_offset

    existing = Measurement.where(token: @measurement.generate_token).first

    @measurement = existing if existing

    @errors = @measurement.save ? nil : @measurement.errors.full_messages.to_sentence
    
    render :show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measurement
      @measurement = Measurement.find(params[:id]) if params[:id]
      @member = current_user
    end

    # Only allow a trusted parameter "white list" through.
    def measurement_params
      params.require(:measurement).permit(:note, 
                                          :glucose_value, 
                                          :measured_at, 
                                          :code_number, 
                                          :reading_type, 
                                          :retrieved_at, 
                                          :meter_id, 
                                          :communication_device_id,
                                          :payload,
                                          :measured_at_time_zone)
    end

end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  before_action :set_measurement, only: [:index, :show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  
  load_and_authorize_resource

  # GET /measurement
  def index
    @measurements = Measurement.mine(@member).where(archived_at: nil).order(:measured_at)
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /measurements/1
  def show
  end

  # GET /measurements/new
  def new
    @measurement = Measurement.new
    @member = Member.find(params[:member_id])
  end

  # GET /measurements/1/edit
  def edit
  end

  # POST /measurements
  def create
    @measurement = Measurement.new(measurement_params)
    @measurement.case_manager = current_user if current_user.is_a? CaseManager
    @measurement.retrieved_at = Time.now unless @measurement.retrieved_at

     if params[:measurement][:archive] == "1"
      @measurement.archive
    else
      @measurement.unarchive
    end

    if @measurement.save
      redirect_to member_measurements_path(@member), notice: 'measurement was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /measurements/1
  def update

    if params[:measurement][:archive] == "1"
      @measurement.archive
      @measurement.save
    else
      @measurement.unarchive
      @measurement.save
    end

    if @measurement.update(measurement_params)
      redirect_to member_measurements_path(@member), notice: 'measurement was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /measurements/1
  def destroy
    @measurement.destroy
    redirect_to measurements_url, notice: 'measurement was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measurement
      @measurement = Measurement.find(params[:id]) if params[:id]
      @member = Member.find(params[:member_id])
    end

    # Only allow a trusted parameter "white list" through.
    def measurement_params
      params.require(:measurement).permit(:note, :measured_at_time_zone, :glucose_value, :measured_at, :code_number, :reading_type, :member_id)
    end

end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/views/measurements/_form.html.erb
<%= simple_form_for([@member, @measurement]) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <label for="title"><%= f.label :glucose_value %></label>
    <%= f.number_field :glucose_value, :class => "form-control", :placeholder => "Enter glucose value"  %>
  </div>

  <div class="form-group">
    <label for="title"><%= f.label :measured_at %></label>
    <%= f.datetime_select :measured_at, :class => "form-control", :placeholder => "Enter measured_at"  %>
  </div>

  <div class="form-group">
    <label for="title"><%= f.label :measured_at_time_zone %></label>
    <%= f.text_field :measured_at_time_zone, :class => "form-control", :placeholder => "Enter time zone"  %>
  </div>

  <div class="form-group">
    <label for="title"><%= f.label :code_number %></label>
    <%= f.number_field :code_number, :class => "form-control", :placeholder => "Enter code number"  %>
  </div>

  <div class="form-group">
    <label for="title"><%= f.label :reading_type %></label>
    <%= f.text_field :reading_type, :class => "form-control", :placeholder => "Enter reading type"  %>
  </div>

  <!-- Meter -->
  <div class="form-group">
    <label for="title"><%= f.label :reading_type %></label>
    <%= f.text_field :reading_type, :class => "form-control", :placeholder => "Enter reading type"  %>
  </div>

  <div class="form-group">
    <label for="title"><%= f.label :note %></label>
    <%= f.text_area :note, :class => "form-control", :placeholder => "Enter a note"  %>
  </div>

  <div class="form-group">
    <label for="title"><%= f.label :is_archived? %></label>
    <%= check_box("measurement", "archive", checked: @measurement.archived? ? true : false)  %>
  </div>

  <input type="hidden" name="measurement[member_id]" value="<%= @member.id %>">

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/measurements/_table.html.erb
<%= javascript_tag do %>
  window.member_id = '<%= @member.id %>';
<% end %>

<div class="row" ng-controller="MeasurementsTableCtrl" ng-cloak>
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-12">
        <nvd3-discrete-bar-chart
            data="chartData"
            id="exampleId"
            xAxisTickFormat="xAxisTickFormatFunction()"
            height="200"
            showXAxis="false"
            showYAxis="true"
            interactive="true"
            color="colorFunction()"
            tooltips="true"
            staggerlabels="true">
                <svg></svg>
        </nvd3-discrete-bar-chart>
      </div>
    </div>
        
    <div class="row text-center">
      <div class="col-md-2 col-md-offset-2">
        <b>Maximum</b> {{max_measurement.glucose_value}} mg/dL
      </div>
      <div class="col-md-2 col-md-offset-1">
        <b>Minimum</b> {{min_measurement.glucose_value}} mg/dL
      </div>
      <div class="col-md-2 col-md-offset-1">
        <b>Average</b> {{total_value / measurements.length | number:2}} mg/dL
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-8">
            <h1><i class="fa fa-stethoscope"></i> Measurements</h1>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <div class="col-md-12">
                <select data-ng-model="search.dateRange" class="form-control">
                  <option value="">All time</option>
                  <option value="1">1 day</option>
                  <option value="2">2 days</option>
                  <option value="3">3 days</option>
                  <option value="7">1 week</option>
                  <option value="14">2 weeks</option>
                  <option value="28">1 month</option>
                  <option value="56">2 months</option>
                  <option value="84">3 months</option>
                  <option value="112">4 months</option>
                  <option value="168">6 months</option>
                  <option value="336">1 year</option>
                </select> 
              </div>
            </div>
          </div>
        </div>
        <div class="row">
            <table class='table col-md-12 table-hover table-condensed' ng-table="tableParams">
              <tbody>
                  <tr ng-repeat="measurement in $data" 
                  ng-class="{'danger': measurement.glucose_value >= 126, 'warning': (measurement.glucose_value < 126 || measurement.glucose_value >= 101)}" 
                  >
                    <td data-title="'Measured At'" sortable="'measured_at'" data-ng-bind-html="measurement.links.show"></td>
                    <td data-title="'Glucose Value'" sortable="'glucose_value'">{{measurement.glucose_value | glucoseValueFilter }}</td>
                    <td data-title="'Reading Type'" sortable="'reading_type'">{{measurement.reading_type | glucoseTypeFilter}}</td>
                  </tr>
              </tbody>
            </table>
        </div>
        <p><strong>Total measurements:</strong> {{tableParams.total()}}</p>
      </div>
    </div>
</div>
</div>

app/views/measurements/edit.html.erb
<h1>Editing measurement</h1>

<%= render 'form' %>

<%= link_to 'Show', member_measurement_path(@member, @measurement) %> |
<%= link_to 'Back', member_measurements_path %>

app/views/measurements/index.html.erb
<%= render 'table' %>

<%= link_to 'New Measurement', new_member_measurement_path if current_user.is_a? CaseManager %>

app/views/measurements/new.html.erb
<h1>New measurement</h1>

<%= render 'form' %>

<%= link_to 'Back', member_measurements_path %>

app/views/measurements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Glucose Value:</strong>
  <%= @measurement.glucose_value %>
</p>

<p>
  <strong>Measured At:</strong>
  <%= @measurement.measured_at %>
</p>

<p>
  <strong>Retrieved At:</strong>
  <%= @measurement.retrieved_at %>
</p>

<p>
  <strong>Retrieved At Time Zone:</strong>
  <%= @measurement.retrieved_at_time_zone %>
</p>

<p>
  <strong>created at:</strong>
  <%= @measurement.created_at %>
</p>

<p>
  <strong>Code Number:</strong>
  <%= @measurement.code_number %>
</p>

<p>
  <strong>Reading Type:</strong>
  <%= @measurement.reading_type %>
</p>

<p>
  <strong>Communication Device Id:</strong>
  <%= @measurement.communication_device_id %>
</p>

<p>
  <strong>Meter Id:</strong>
  <%= @measurement.meter_id %>
</p>

<p>
  <strong>Note:</strong>
  <%= @measurement.note %>
</p>

<p>
  <strong>User id:</strong>
  <%= @measurement.user_id %>
</p>

<%= link_to 'Edit', edit_measurement_path(@measurement) %> |
<%= link_to 'Back', measurements_path %>