config/routes.rb
Mew::Application.routes.draw do

  ActiveAdmin.routes(self)
  namespace :api, :constraints => {:format => /(json)/} do
    namespace :v1 do
      devise_for :users, controllers: {:sessions => 'api/v1/users/sessions'}
      resources :meters, only: [:create]
      
      resources :measurements, only: [:create, :show, :index, :update]
      resources :communication_devices, only: [:create, :show, :update]

      resources :reports
      match '/reports/:id/run' => 'reports#run', via: [:get], as: :api_v1_run_report
    end
  end

  resources :case_managers do 
    resources :managed_members, only: [:index, :create, :destroy]
  end

  resources :member_groups, except: [:show] do
    resources :grouped_members, only: [:index, :create, :destroy]
  end

  resources :reports

  resources :members do
    resources :email_messages, only: [:index, :create, :new, :show]
    resources :measurements
    resources :case_managers, only: [:index]
  end

  devise_for :users, controllers: {:sessions => 'users/sessions', :registrations => 'users/registrations'}
  resources :communication_devices
  resources :meters

  root 'high_voltage/pages#show', id: 'home'
end

app/models/member.rb
class Member < User
  include Archivable

	validates :phone_number, presence: true
	validates :member_number, presence: true
	
  has_many :measurements

  has_and_belongs_to_many :meters
  has_many :case_managers, through: :managed_members

  belongs_to :preferred_meter, class_name: "Meter"
  
  has_many :managed_members
  has_many :grouped_members

  def self.mine(case_manager)
    if case_manager.has_role? :case_manager_admin
      all
    else
      joins(:managed_members).where("managed_members.case_manager_id = ?", case_manager.id)
    end
  end

  def measurement_count_last_days(days)
    self.measurements.map{|m| m if (m.measured_at > (Time.now - days.days)) and m.archived_at.nil? }.compact.length
  end

  def primary_case_manager
    managed_member = (managed_members.select {|n| n.primary }).first
    managed_member ||= managed_members.first
    managed_member.case_manager if managed_member
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  load_and_authorize_resource
  
  # GET /members
  def index
    if params[:not_in_member_group_id]
      @members = Member.mine(current_user).where(
                   GroupedMember.select(:NULL).where("member_group_id = ? and grouped_members.member_id = users.id", params[:not_in_member_group_id]).exists.not)
    elsif params[:not_managed_by_case_manager_id]
      @members = Member.mine(current_user).where(
                   ManagedMember.select(:NULL).where("case_manager_id = ? and managed_members.member_id = users.id", params[:not_managed_by_case_manager_id]).exists.not)
    else
      @members = Member.includes(:measurements, :managed_members).mine(current_user)
    end

    respond_to do |format|
      format.html
      format.json 
    end
  end

  # GET /members/1
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  def create
    @member = Member.new(member_params)

    @member.password = "password"
    if params[:member][:archive] == "1"
      @member.archive
    else
      @member.unarchive
    end
    if @member.save
      redirect_to @member, notice: 'Member was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /members/1
  def update
   if params[:member][:archive] == "1"
      @member.archive
      @member.save
    else
      @member.unarchive
      @member.save
    end
    if @member.update(member_params)
      redirect_to @member, notice: 'Member was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /members/1
  def destroy
    @member.destroy
    redirect_to members_url, notice: 'Member was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :email, :phone_number, :member_number, :note)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= simple_form_for(@member, autocomplete: "off") do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <label for="title"><%= f.label :first_name %></label>
    <%= f.text_field :first_name, :class => "form-control", :placeholder => "Enter first name"  %>
  </div>

  <div class="form-group">
    <label for="title"><%= f.label :last_name %></label>
    <%= f.text_field :last_name, :class => "form-control", :placeholder => "Enter last name"  %>
  </div>

  <div class="form-group">
    <label for="title"><%= f.label :phone_number %></label>
    <%= f.phone_field :phone_number, :class => "form-control", :placeholder => "Enter phone number"  %>
  </div>

  <div class="form-group">
    <label for="title"><%= f.label :member_id %></label>
    <%= f.text_field :member_number, :class => "form-control", :placeholder => "Enter member number"  %>
  </div>

  <div class="form-group">
    <label for="title"><%= f.label :email %></label>
    <%= f.email_field :email, :class => "form-control", :placeholder => "Enter email"  %>
  </div>

  <div class="form-group">
    <label for="title"><%= f.label :notes %></label>
    <%= f.text_area :note, :class => "form-control", :placeholder => "Enter notes"  %>
  </div>

  <div class="form-group">
    <label for="title"><%= f.label :is_archived? %></label>
    <%= check_box("member", "archive", checked: @member.archived? ? true : false)  %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<div ng-controller="MembersTableCtrl" ng-cloak>
  <div class="row">
    <div class="col-md-6">
      <h1><i class="fa fa-user"></i> Members</h1>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label class="col-md-1 control-label search-label">Find</label>
        <div class="col-md-10">
          <input type="search" ng-model="filter.$" class="form-control search-box" />
        </div>
      </div>
    </div>
  </div>

  <table class='table table-hover table-condensed' ng-table="tableParams">
    <tbody>
        <tr ng-repeat="member in $data">
          <td data-title="'Name'" sortable="'name'" data-ng-bind-html="member.links.show"></td>
          <td data-title="'Member ID'" sortable="'email'">{{member.member_number}}</td>
          <td data-title="'Total Measurements'" sortable="'measurement_count'" data-ng-bind-html="member.links.measurement_count"></td>
          <td data-title="'Measurements in the last 28 days'" sortable="'measurement_count_last_28_days'">{{member.measurement_count_last_28_days}}</td>
        </tr>
    </tbody>
  </table>
  <p><strong>Total members:</strong> {{tableParams.total()}}</p>
</div>
<%= link_to 'New Member', new_member_path if current_user.has_role? :case_manager_admin  %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="row">
      <div class="col-md-12 well">
        <h2><i class="fa fa-user"></i> <%= @member.display_name %></h2><%= link_to 'Edit', edit_member_path(@member) %>
        <p>ID: <%= @member.member_number %></p>
        <p>Phone: <%= number_to_phone @member.phone_number %></p>
        <p><%= link_to 'Message history', member_email_messages_path(@member), class: "btn btn-primary" %> <%= link_to 'Contact', new_member_email_message_path(@member), class: "btn btn-success" %> </p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 well">
        <h2>Alerts</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 well">
        <h2>Notes</h2>
        <%= form_for @member do |f| %>
          <div class="form-group">
            <%= f.text_area :note, :class => "form-control", :placeholder => "Enter notes", style: "width: 100%; height: 250px", cols: "20"  %>
          </div>

          <div class="actions">
            <%= f.button :Save, class: "btn btn-default" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 well">
        <h2><i class="fa fa-user-md"></i>Case Managers</h2>
        <table class="table">
        <th>
          <tr>
            <td>Name</td>
            <td></td>
          </tr>
        </th>
        <tbody>
          <% @member.managed_members.each do |managed_members| %>
          <tr>
            <td><%= managed_members.case_manager.display_name %></td>
            <td><% if managed_members.primary %><span class="label label-success">Primary</span><% end %></td>
          </tr>
          <% end %>
        </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-md-8 col-md-offset-1">
     <div class="row">
      <div class="col-md-12 well">
        <%= render 'measurements/table' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 well">
        <%= render 'meters/table' %>
      </div>
    </div>
  </div>
</div>